# 내장함수 - 수치데이터 관련 내장함수들
# [1] 절대값 변환 내장함수: abs()
print(f'-4의 절대값: {abs(-4)}')
print(f'-4.5의 절대값: {abs(-4.5)}')
# [2] 최대값 반환 내장함수: max(데이터, 데이터1, ...)
print(f'-4와 9의 최대값: {max(-4,9)}')
print(f'a, A, b, B의 최대값: {max("a","A","b", "B")}')
# [3] 최소값 반환 내장함수: min(데이터, 데이터1, ...)
print(f'-4와 9의 최소값: {min(-4,9)}')
print(f'a, A, b, B의 최소값: {min("a","A","b", "B")}')
# [4] 거듭제곱 내장함수: pow(int, int1)
print(f'2의 5승: {pow(2,5)}')
print(f'-1의 2승: {pow(-1,2)}')
# [5] 반올림 내장함수: round(float)
num=3.141592
round()
print(f'{num}의 소수점 1번째 자리에서 반올림: {round(num)}')
print(f'{num}의 소수점 2번째 자리에서 반올림: {round(num,0)}')
print(f'{num}의 소수점 3번째 자리에서 반올림: {round(num,1)}')
print(f'{num}의 소수점 4번째 자리에서 반올림: {round(num,2)}')
print(f'{num}의 소수점 5번째 자리에서 반올림: {round(num,3)}')
print(f'{num}의 소수점 6번째 자리에서 반올림: {round(num,4)}')